-- ============================================
-- TABLAS DE USUARIOS - A.L.M.A (PostgreSQL)
-- Versión Simple - Sistema de Organizaciones
-- ============================================

-- Organizaciones (Sanitas, Hospital La Paz, etc.)
-- DEBE CREARSE PRIMERO porque USUARIO tiene FK a esta tabla
CREATE TABLE ORGANIZACION (
    ID_ORGANIZACION SERIAL,
    NOMBRE_ORGANIZACION VARCHAR(150),
    CIF VARCHAR(9),
    EMAIL_CONTACTO VARCHAR(100),
    TELEFONO_CONTACTO VARCHAR(15),
    ACTIVA BOOLEAN DEFAULT TRUE,
    FECHA_ALTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_ORGANIZACION PRIMARY KEY (ID_ORGANIZACION),
    CONSTRAINT NN_NOMBRE_ORGANIZACION CHECK (NOMBRE_ORGANIZACION IS NOT NULL),
    CONSTRAINT NN_CIF CHECK (CIF IS NOT NULL),
    CONSTRAINT UQ_CIF UNIQUE (CIF)
);

-- Tabla principal de usuarios
-- Todos los usuarios (PACIENTE, PROFESIONAL, ADMIN_ORGANIZACION, SUPER_ADMIN) pertenecen a una organización
CREATE TABLE USUARIO (
    ID_USUARIO SERIAL,
    EMAIL VARCHAR(100),
    PASSWORD_HASH VARCHAR(255),
    NOMBRE VARCHAR(50),
    APELLIDOS VARCHAR(100),
    TIPO_USUARIO VARCHAR(20), -- PACIENTE, PROFESIONAL, ADMIN_ORGANIZACION, SUPER_ADMIN
    organizacion_id INTEGER NOT NULL,
    ACTIVO BOOLEAN DEFAULT TRUE,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ULTIMO_ACCESO TIMESTAMP,
    PASSWORD_TEMPORAL BOOLEAN DEFAULT TRUE,

    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT NN_EMAIL CHECK (EMAIL IS NOT NULL),
    CONSTRAINT NN_PASSWORD_HASH CHECK (PASSWORD_HASH IS NOT NULL),
    CONSTRAINT NN_NOMBRE CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT NN_TIPO_USUARIO CHECK (TIPO_USUARIO IS NOT NULL),
    CONSTRAINT UQ_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_TIPO_USUARIO CHECK (TIPO_USUARIO IN ('PACIENTE', 'PROFESIONAL', 'ADMIN_ORGANIZACION', 'SUPER_ADMIN')),
    CONSTRAINT FK_USUARIO_ORGANIZACION FOREIGN KEY (organizacion_id) REFERENCES ORGANIZACION(ID_ORGANIZACION)
);

-- Tabla de Profesionales (vinculados a una organización)
CREATE TABLE PROFESIONAL (
    ID_PROFESIONAL SERIAL,
    ID_USUARIO INTEGER,
    NUMERO_COLEGIADO VARCHAR(20),
    ESPECIALIDAD VARCHAR(100),
    
    CONSTRAINT PK_PROFESIONAL PRIMARY KEY (ID_PROFESIONAL),
    CONSTRAINT NN_ID_USUARIO_PROF CHECK (ID_USUARIO IS NOT NULL),
    CONSTRAINT UQ_ID_USUARIO_PROFESIONAL UNIQUE (ID_USUARIO),
    CONSTRAINT UQ_NUMERO_COLEGIADO UNIQUE (NUMERO_COLEGIADO),
    CONSTRAINT FK_PROFESIONAL_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

-- Tabla de Pacientes
CREATE TABLE PACIENTE (
    ID_PACIENTE SERIAL,
    ID_USUARIO INTEGER,
    FECHA_NACIMIENTO DATE,
    GENERO VARCHAR(20),
    
    CONSTRAINT PK_PACIENTE PRIMARY KEY (ID_PACIENTE),
    CONSTRAINT NN_ID_USUARIO_PAC CHECK (ID_USUARIO IS NOT NULL),
    CONSTRAINT UQ_ID_USUARIO_PACIENTE UNIQUE (ID_USUARIO),
    CONSTRAINT CK_GENERO CHECK (GENERO IN ('MASCULINO', 'FEMENINO', 'NO_BINARIO', 'PREFIERO_NO_DECIR')),
    CONSTRAINT FK_PACIENTE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

-- Relación: qué profesional atiende a qué paciente
CREATE TABLE ASIGNACION_PROFESIONAL_PACIENTE (
    ID_ASIGNACION SERIAL,
    ID_PROFESIONAL INTEGER,
    ID_PACIENTE INTEGER,
    ES_PRINCIPAL BOOLEAN DEFAULT TRUE, -- Si es el profesional principal del paciente
    FECHA_ASIGNACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT TRUE,
    
    CONSTRAINT PK_ASIGNACION PRIMARY KEY (ID_ASIGNACION),
    CONSTRAINT NN_ID_PROFESIONAL_ASIG CHECK (ID_PROFESIONAL IS NOT NULL),
    CONSTRAINT NN_ID_PACIENTE_ASIG CHECK (ID_PACIENTE IS NOT NULL),
    CONSTRAINT FK_ASIGNACION_PROFESIONAL FOREIGN KEY (ID_PROFESIONAL) REFERENCES PROFESIONAL(ID_PROFESIONAL),
    CONSTRAINT FK_ASIGNACION_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)
);

-- Relación: qué admin pertenece a qué organización
CREATE TABLE ADMIN_ORGANIZACION (
    ID_ADMIN SERIAL,
    ID_USUARIO INTEGER,
    ID_ORGANIZACION INTEGER,
    
    CONSTRAINT PK_ADMIN_ORGANIZACION PRIMARY KEY (ID_ADMIN),
    CONSTRAINT NN_ID_USUARIO_ADMIN CHECK (ID_USUARIO IS NOT NULL),
    CONSTRAINT NN_ID_ORGANIZACION_ADMIN CHECK (ID_ORGANIZACION IS NOT NULL),
    CONSTRAINT UQ_ID_USUARIO_ADMIN_ORG UNIQUE (ID_USUARIO),
    CONSTRAINT FK_ADMIN_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK_ADMIN_ORGANIZACION FOREIGN KEY (ID_ORGANIZACION) REFERENCES ORGANIZACION(ID_ORGANIZACION)
);

-- ============================================
-- COMENTARIOS (DOCUMENTACIÓN)
-- ============================================

COMMENT ON TABLE USUARIO IS 'Tabla principal de todos los usuarios del sistema';
COMMENT ON COLUMN USUARIO.PASSWORD_TEMPORAL IS 'Si es TRUE, el usuario debe cambiar su contraseña en el próximo inicio de sesión.';
COMMENT ON TABLE ORGANIZACION IS 'Organizaciones B2B/B2G que contratan el servicio A.L.M.A';
COMMENT ON TABLE PROFESIONAL IS 'Profesionales de salud mental vinculados a organizaciones';
COMMENT ON TABLE PACIENTE IS 'Pacientes en proceso de duelo atendidos por profesionales';
COMMENT ON TABLE ASIGNACION_PROFESIONAL_PACIENTE IS 'Asignación de pacientes a profesionales';
COMMENT ON TABLE ADMIN_ORGANIZACION IS 'Administradores que gestionan profesionales y pacientes de una organización';